### ISSUE TITLE
Read-only global 'location' should not be modified

### ISSUE THREAD

**Issue by pdehaan** [mozilla/inhuman-ads-webext#1]
... or so says ESLint.

```yml
# .eslintrc.yml
env:
  browser: true
  es6: true
  jquery: true
  webextensions: true

extends:
  - eslint:recommended

globals:
  auth: false
  buildSettings: false
  callBackground: false
  catcher: false
  communication: false
  getSettings: false
  log: false  
  main: false
  makeUuid: false

root: true

rules:
  eqeqeq: error
  no-console: warn
  no-unused-vars: [error, {vars: all, args: none}]
  quotes: [off, double] # TODO: Set to warn?
```

Current output:

```sh
$ npm run lint

> inhuman-ads-webext@1.0.0 lint /Users/pdehaan/dev/tmp/del/inhuman-ads-webext
> eslint .

/Users/pdehaan/dev/tmp/del/inhuman-ads-webext/background/auth.js
  49:26  error  Expected '===' and instead saw '=='  eqeqeq
  85:26  error  Expected '===' and instead saw '=='  eqeqeq

/Users/pdehaan/dev/tmp/del/inhuman-ads-webext/common/getSettings.js
  15:27  error  Expected '===' and instead saw '=='  eqeqeq

/Users/pdehaan/dev/tmp/del/inhuman-ads-webext/content/main.js
  14:65  error    Expected '!==' and instead saw '!='                 eqeqeq
  25:12  error    'foo' is assigned a value but never used            no-unused-vars
  28:9   error    Read-only global 'location' should not be modified  no-global-assign
  30:9   warning  Unexpected console statement                        no-console
  46:24  error    Expected '===' and instead saw '=='                 eqeqeq
  55:11  error    Read-only global 'location' should not be modified  no-global-assign
  58:9   warning  Unexpected console statement                        no-console
  72:9   warning  Unexpected console statement                        no-console

✖ 11 problems (8 errors, 3 warnings)
  1 error, 0 warnings potentially fixable with the `--fix` option.
```
